### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by grodowski** [codequest-eu/codequest_pipes#10]
- `Context#halt` is unusable, because it does not stop the check for `provide_context`.

**Comment by panyarerk098** [comment]
Who mak i don't know you i my page it be new account for looking bad hack me if it delet  i get it is people  to dangerous in world trade inot give pull to panyareksakunchai@gmail.com why give it pull go make is account it because before to i see it delet my numbers moblie get and it using gmail.com it doing i cannot reset password and it is ? I personally in google play too ads  it i not want see if all apps are same i get that is bad,  though,not has cut off it from trade and computer to it make every day of it bruning  in digital mode what way it have and useing console me see tool to i set up so open source software and code it fix the problem with company to have name i change before trade it useing? Taking disk it and make backup sure wrining all frind it wil not stop if it delet i not get back to it registered after i wrong  too i testing something now TV to my home it have index 2 set key feed to my browser Google every time it takes me not happy because Tv is android it fix problems with me now who go to home it or hotels it get adjusted it by police it not know right or though to be.....my home tell it bad dogecoin it will make getting to where glod kiness yes me to is friends you or not stop it too if you know me not make to that don't call black provided it get glod you i not have time taking care of my family me.sick but will working with frind to help us find out how it works?
